#pragma config(Sensor, in1,    lnR,      sensorLineFollower)
#pragma config(Sensor, in2,    lnL,    sensorLineFollower)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!

#include "autonomous.c" //Agrega las funciones autonomas del robot.
#pragma systemFile            // eliminates warning for "unreferenced" functions
//precode

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
//
//
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	//autoAdelante(-1); //Lado rojo = 1, Lado azul = -1
	autoAtras(-1); //Lado azul = 1, Lado rojo = -1
	//orugaEscupe(127);
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
//
//
//
/////////////////////////////////////////////////////////////////////////////////////////

/////////////////////////////////////////////////////////////////////////////////////////
// Funcion principal: Declara los joysticks para mover las llantas lado derecho y izquierdo.
/////////////////////////////////////////////////////////////////////////////////////////
task robotMove()
{
    while( true )
        {
		      motor[port2] = vexRT[Ch2];
				  motor[port3]  = vexRT[Ch2];
				  motor[port4] = vexRT[Ch3];
				  motor[port5]  = vexRT[Ch3];
        }
}

task usercontrol()
{
	startTask( robotMove );

	// Loop de Control
	while (true)
	{
		// .....................................................................................
	  // Si el botton boton 5U esta precionado, traga bolas.
	  // .....................................................................................
		if(vexRT[Btn5U]==1) {
	    motor[port9] = 127;
	  }
		// .....................................................................................
	  // Si el botton boton 5D esta precionado, escupe bolas.
	  // .....................................................................................
		else if(vexRT[Btn5D]==1) {
		  motor[port9] = -127;
		}
		// .....................................................................................
	  // Si el botton boton 6U esta precionado, levanta el brazo.
	  // .....................................................................................
		if(vexRT[Btn6U]==1) {
			if(SensorValue[dgtl4]==0){
	    		motor[port1] = 0;
		    	motor[port10]  = 0;
	    	}
	    else {
	    		motor[port1] = 127;
					motor[port10]  = 127;
			}
	  }
		// .....................................................................................
	  // Si el botton boton 6D esta precionado, baja el brazo.
	  // .....................................................................................
		else if(vexRT[Btn6D]==1) {
			if(SensorValue[dgtl3]==0){
		    motor[port1] = 0;
			  motor[port10]  = 0;
		  }
		  else {
		    motor[port1] = -127;
				motor[port10]  = -127;
			}
		}
		// .....................................................................................
	  // Si el botton boton 8U esta precionado, sube el gancho.
	  // .....................................................................................
		else if(vexRT[Btn7U]==1) {
	    motor[port8] = 127;
	  }
		// .....................................................................................
	  // Si el botton boton 8D esta precionado, baja el gancho.
	  // .....................................................................................
		else if(vexRT[Btn7D]==1) {
	    motor[port8] = -127;
		}
				// .....................................................................................
	  // Si el botton boton 8U esta precionado, rueda transversal lado derecho.
	  // .....................................................................................
		else if(vexRT[Btn8R]==1) {
	    motor[port7] = 55;
	  }
		// .....................................................................................
	  // Si el botton boton 8D esta precionado, rueda transversal lado izquierdo.
	  // .....................................................................................
		else if(vexRT[Btn8L]==1) {
		 	motor[port7] = -55;
		}
		else {
			motor[port1] = 0;
			motor[port7] = 0;
			motor[port8]  = 0;
			motor[port9]  = 0;
			motor[port10]  = 0;
		}
  }
}
