#pragma config(Sensor, in1,    lnR,      sensorLineFollower)
#pragma config(Sensor, in2,    lnL,    sensorLineFollower)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX)

//Competition Control and Duration Settings
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)

#include "Vex_Competition_Includes.c"   //Main competition background code...do not modify!
//precode


/////////////////////////////////////////////////////////////////////////////////////////
//
//                          Pre-Autonomous Functions
//
// You may want to perform some actions before the competition starts. Do them in the
// following function.
//
/////////////////////////////////////////////////////////////////////////////////////////
void brazoUp()
{
	int a=0;
	while (a==0){
		if(SensorValue[dgtl4]==0){
			a=1;
	    motor[port1] = 0;
		  motor[port10]  = 0;
		}
		else {
			motor[port1] = 127;
			motor[port10]  = 127;
		}
	}
}
void brazoDown()
{
	int a=0;
	while (a==0){
		if(SensorValue[dgtl3]==0){
			a=1;
	    motor[port1] = 0;
		  motor[port10]  = 0;
		}
		else {
			motor[port1] = -127;
			motor[port10]  = -127;
		}
	}
}
void brazoDownMed()
{
	motor[port1] = -127;
	motor[port10]  = -127;
	wait1Msec(200);
	motor[port1] = 0;
	motor[port10]  = 0;

}
void brazoUpMed(float tiempo)
{
	motor[port1] = 127;
	motor[port10]  = 127;
	wait1Msec(tiempo*1000);
	motor[port1] = 0;
	motor[port10]  = 0;

}
void adelante(int velocidad, float tiempo, int brazo)
{
		motor[port2] = velocidad/4;
    motor[port3] = velocidad/4;
	  motor[port4] = velocidad/4;
    motor[port5] = velocidad/4;
    wait1Msec(200);
    motor[port2] = velocidad/2;
    motor[port3] = velocidad/2;
	  motor[port4] = velocidad/2;
    motor[port5] = velocidad/2;
    wait1Msec(200);

    while(SensorValue[dgtl1]==1 && SensorValue[dgtl5]==1) {
    	motor[port2] = velocidad;
	    motor[port3] = velocidad;
		  motor[port4] = velocidad;
	    motor[port5] = velocidad;
	    if (brazo==1) {
	    	brazoUp();
	  	}
  	}

    motor[port2] = velocidad;
    motor[port3] = velocidad;
	  motor[port4] = velocidad;
    motor[port5] = velocidad;

		wait1Msec(tiempo*1000);

    motor[port2] = 0;
    motor[port3] = 0;
	  motor[port4] = 0;
    motor[port5] = 0;
}
void adelanteTiempo(int velocidad, float tiempo, int brazo)
{
		motor[port2] = velocidad/4;
    motor[port3] = velocidad/4;
	  motor[port4] = velocidad/4;
    motor[port5] = velocidad/4;
    wait1Msec(200);
    motor[port2] = velocidad/2;
    motor[port3] = velocidad/2;
	  motor[port4] = velocidad/2;
    motor[port5] = velocidad/2;
    wait1Msec(200);
    if (brazo==1) {
    	brazoUp();
  	}

    motor[port2] = velocidad;
    motor[port3] = velocidad;
	  motor[port4] = velocidad;
    motor[port5] = velocidad;

		wait1Msec(tiempo*1000);

    motor[port2] = 0;
    motor[port3] = 0;
	  motor[port4] = 0;
    motor[port5] = 0;
}
void transversal(int velocidad, float tiempo, int brazo)
{
		motor[port7] = velocidad/4;
    wait1Msec(200);
    motor[port7] = velocidad/2;
    wait1Msec(200);
    if (brazo==1) {
    	brazoUp();
  	}

    motor[port7] = velocidad;

		wait1Msec(tiempo*1000);

    motor[port7] = 0;
}
void atras(int velocidad, float tiempo, int brazo)
{
    motor[port2] = -velocidad;
    motor[port3]  = -velocidad;
	  motor[port4] = -velocidad;
    motor[port5]  = -velocidad;
		if (brazo==1){
				brazoUpMed(1.2);
		}
		wait1Msec(tiempo*1000);

    motor[port2] = 0;
    motor[port3]  = 0;
	  motor[port4] = 0;
    motor[port5]  = 0;
}
void click()
{
	int a=0;
	while (a==0) {
		if(SensorValue[dgtl2]==0){
			a=1;
		}
	}
}
void orugaTraga(int velocidad)
{
	motor[port9]=-velocidad;
}
void orugaEscupe(int velocidad)
{
	motor[port9]=velocidad;
}
void orugaOff()
{
	motor[port9]=0;
}
void adelanteLine(int velocidad, int lado)
{
	int turnLeft=0;
	int turnRight=0;
		motor[port2] = velocidad;
    motor[port3]  = velocidad;
	  motor[port4] = velocidad;
    motor[port5]  = velocidad;
    wait1Msec(1000);
    if (lado==-1) {
			while(SensorValue[lnL]>2960) {
				motor[port2] = velocidad;
		    motor[port3]  = velocidad;
			  motor[port4] = velocidad;
		    motor[port5]  = velocidad;
			}
		}
		else {
			while(SensorValue[lnR]>2900) {
				motor[port2] = velocidad;
		    motor[port3]  = velocidad;
			  motor[port4] = velocidad;
		    motor[port5]  = velocidad;
			}
		}
	  motor[port2] = velocidad * lado;
    motor[port3] = velocidad * lado;
	  motor[port4] = -velocidad * lado;
    motor[port5] = -velocidad* lado;
    wait1Msec(160);
    motor[port2] = 0;
    motor[port3]  = 0;
    motor[port4] = 0;
    motor[port5]  = 0;
    brazoUp();

	  while(SensorValue[dgtl1]==1 && SensorValue[dgtl5]==1 && SensorValue[dgtl6]==1) {
			motor[port2] = velocidad/2-turnLeft;
	    motor[port3]  = velocidad/2-turnLeft;
		  motor[port4] = velocidad/2-turnRight;
	    motor[port5]  = velocidad/2-turnRight;
	    if (SensorValue[lnR]<2900) {
	    	turnLeft=velocidad/2;
			}
			else if (SensorValue[lnL]<2960) {
	    	turnRight=velocidad/2;
			}
			else {
				turnLeft=0;
				turnRight=0;
			}
		}
    motor[port2] = 0;
    motor[port3]  = 0;
    motor[port4] = 0;
    motor[port5]  = 0;
}
void girar(int velocidad,float tiempo, int lado) {
	motor[port2]= velocidad;
	motor[port3]= velocidad;
	motor[port4]= -velocidad;
	motor[port5]= -velocidad;
	wait1Msec(tiempo * 1000);
	motor[port2]= 0;
	motor[port3]= 0;
	motor[port4]= 0;
	motor[port5]= 0;
}
void autoAdelante(int lado) {
	//brazoUp();
	//adelante(127, 0, 0); //3 espacio: Levantar brazo mientras avanza =1,
	//brazoDownMed();
	//atras(127, 1.5, 0);
	//brazoDown();
	//click();
	//adelante(127, 0, 1);
	//brazoDownMed();
	//atras(127, 1.5, 0);
	//brazoDown();
	//click();
	//adelanteTiempo(127, 1.5, 0); //Levantar brazo mientras avanza =1,
	////adelanteLine(127, lado); //Lado Derecho = 1, Lado Izquierdo = -1
	adelanteTiempo(127, 1.5, 0); //Levantar brazo mientras avanza =1,
	orugaEscupe(127);
}
void autoAtras(int lado) {
	orugaTraga(127);
	adelanteTiempo(127, 0.4, 0); //Levantar brazo mientras avanza =1,
  wait1Msec(200);
	orugaOff();
	//girar(127, 0.4, 1);
	transversal((65*lado), 2, 0);
	atras(127, 1.1, 0);
	transversal((65*lado), 1.6, 0);
	adelanteTiempo(127, 0.6, 0); //Levantar brazo mientras avanza =1,
	atras(127, 1.3, 0); //brazoupMed 1
	adelanteTiempo(127, 0.5, 0); //Levantar brazo mientras avanza =1,
	transversal((65*lado), 1, 0);
	atras(127, 1, 0);
}

void pre_auton()
{
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false.
  bStopTasksBetweenModes = true;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 Autonomous Task
//
// This task is used to control your robot during the autonomous phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

task autonomous()
{
	//autoAdelante(-1); //Lado rojo = 1, Lado azul = -1
	autoAtras(-1); //Lado azul = 1, Lado rojo = -1
	//orugaEscupe(127);
}

/////////////////////////////////////////////////////////////////////////////////////////
//
//                                 User Control Task
//
// This task is used to control your robot during the user control phase of a VEX Competition.
// You must modify the code to add your own robot specific commands here.
//
/////////////////////////////////////////////////////////////////////////////////////////

// .....................................................................................
// Funcion principal: Declara los joysticks para mover el lado derecho y izquierdo.
// .....................................................................................
task robotMove()
{
    while( true )
        {
		      motor[port2] = vexRT[Ch2];
				  motor[port3]  = vexRT[Ch2];
				  motor[port4] = vexRT[Ch3];
				  motor[port5]  = vexRT[Ch3];
        }
}

task usercontrol()
{
	StartTask( robotMove );
	// User control code here, inside the loop

	while (true)
	{
		// .....................................................................................
	  // Si el botton boton 5U esta precionado, traga bolas.
	  // .....................................................................................
		if(vexRT[Btn5U]==1) {
	    motor[port9] = 127;
	  }
		// .....................................................................................
	  // Si el botton boton 5D esta precionado, escupe bolas.
	  // .....................................................................................
		else if(vexRT[Btn5D]==1) {
		  motor[port9] = -127;
		}
		// .....................................................................................
	  // Si el botton boton 6U esta precionado, levanta el brazo.
	  // .....................................................................................
		if(vexRT[Btn6U]==1) {
			if(SensorValue[dgtl4]==0){
	    		motor[port1] = 0;
		    	motor[port10]  = 0;
	    	}
	    else {
	    		motor[port1] = 127;
					motor[port10]  = 127;
			}
	  }
		// .....................................................................................
	  // Si el botton boton 6D esta precionado, baja el brazo.
	  // .....................................................................................
		else if(vexRT[Btn6D]==1) {
			if(SensorValue[dgtl3]==0){
		    motor[port1] = 0;
			  motor[port10]  = 0;
		  }
		  else {
		    motor[port1] = -127;
				motor[port10]  = -127;
			}
		}
		// .....................................................................................
	  // Si el botton boton 8U esta precionado, sube el gancho.
	  // .....................................................................................
		else if(vexRT[Btn7U]==1) {
	    motor[port8] = 127;
	  }
		// .....................................................................................
	  // Si el botton boton 8D esta precionado, baja el gancho.
	  // .....................................................................................
		else if(vexRT[Btn7D]==1) {
	    motor[port8] = -127;
		}
				// .....................................................................................
	  // Si el botton boton 8U esta precionado, rueda transversal lado derecho.
	  // .....................................................................................
		else if(vexRT[Btn8R]==1) {
	    motor[port7] = 55;
	  }
		// .....................................................................................
	  // Si el botton boton 8D esta precionado, rueda transversal lado izquierdo.
	  // .....................................................................................
		else if(vexRT[Btn8L]==1) {
		 	motor[port7] = -55;
		}
		else {
			motor[port1] = 0;
			motor[port7] = 0;
			motor[port8]  = 0;
			motor[port9]  = 0;
			motor[port10]  = 0;
		}
  }
}
